# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "ristill_anniversary"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "anniversary.ristill.club"
custom_domain = true

[observability]
enabled = true

# The binding name must be "ASSETS" when the cache is enabled
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# [placement]
# mode = "smart"

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# Production environment configuration
[env.production]
name = "ristill_anniversary-production"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[env.production.routes]]
pattern = "anniversary.ristill.club"
custom_domain = true

[env.production.observability]
enabled = true

[env.production.assets]
directory = ".open-next/assets"
binding = "ASSETS"

# You can override any configuration for production environment here
# [env.production.vars]
# MY_VARIABLE = "production_specific_value" 