name = "ristill_club"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[rules]]
type = "Data"
globs = ["**/*.ttf", "**/*.otf"]
fallthrough = true

[[routes]]
pattern = "ristill.club"
custom_domain = true

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
