name: "Cache Node Modules"
description: "Caches node_modules using actions/cache"
inputs:
  path:
    description: "Path to the node_modules to cache"
    required: true
outputs:
  cache-hit:
    description: A boolean value to indicate an exact match was found for the primary key
    value: ${{ steps.cache_dependency.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache_dependency
      with:
        path: ${{ inputs.path }}
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml', '**/package-lock.json', '**/yarn.lock', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
