name: Validate Rules Synchronization

on:
  schedule:
    # Run every day at 9:00 AM JST (00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      force_sync:
        description: "Force synchronization even if no changes detected"
        required: false
        type: boolean

jobs:
  validate-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Check synchronization status using Claude Code Action
        id: check-sync
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: Bash(pnpm:*),Bash(node:*),Bash(git:*),View,Edit,GlobTool,GrepTool,BatchTool
          direct_prompt: |
            Compare the content of CLAUDE.md with all files in .cursor/rules/ directory and generate a synchronization report.

            Check for:
            1. Missing rules in CLAUDE.md that exist in .cursor/rules
            2. Missing rules in .cursor/rules that exist in CLAUDE.md
            3. Inconsistencies between the two sources
            4. Outdated information in either location

            Generate a markdown report with:
            - Sync status (synchronized/out-of-sync)
            - List of discrepancies found
            - Recommendations for fixes
            - Priority level (high/medium/low) for each issue

            Save the report to sync_report.md file.
            If everything is synchronized, write "SYNCHRONIZED" at the beginning of the report.

      - name: Check sync status from report
        id: check-status
        run: |
          if [ -f sync_report.md ] && grep -q "SYNCHRONIZED" sync_report.md && ! grep -q "out-of-sync\|discrepancies\|missing" sync_report.md; then
            echo "sync_status=synchronized" >> $GITHUB_OUTPUT
            echo "Rules are synchronized"
          else
            echo "sync_status=out-of-sync" >> $GITHUB_OUTPUT
            echo "Synchronization issues detected"
          fi

      - name: Create issue for sync problems
        if: steps.check-status.outputs.sync_status == 'out-of-sync'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const syncReport = fs.readFileSync('sync_report.md', 'utf8');

            // Check if there's already an open issue for sync problems
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'sync-issue,automated'
            });

            const existingIssue = issues.data.find(issue => 
              issue.title.includes('Rules Synchronization Issue')
            );

            const issueBody = `# 🔄 Rules Synchronization Issue Detected

            The automated validation has detected synchronization issues between \`CLAUDE.md\` and \`.cursor/rules/\` files.

            ## Sync Report

            ${syncReport}

            ## Action Required

            Please review the discrepancies and run the appropriate sync workflow:
            - If \`.cursor/rules\` is the source of truth: Manually trigger the "Sync .cursor/rules to CLAUDE.md" workflow
            - If \`CLAUDE.md\` is the source of truth: Manually trigger the "Sync CLAUDE.md to .cursor/rules" workflow

            ## Auto-generated
            This issue was automatically created by the validation workflow.
            Date: ${new Date().toISOString()}

            ---

            - [ ] Review synchronization report
            - [ ] Determine source of truth
            - [ ] Run appropriate sync workflow  
            - [ ] Verify synchronization is complete
            - [ ] Close this issue
            `;

            if (existingIssue) {
              // Update existing issue
              await github.rest.issues.createComment({
                issue_number: existingIssue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🔄 Updated Sync Report - ${new Date().toISOString()}\n\n${syncReport}`
              });
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '🔄 Rules Synchronization Issue Detected',
                body: issueBody,
                labels: ['sync-issue', 'automated', 'high-priority']
              });
            }

      - name: Upload sync report
        uses: actions/upload-artifact@v4
        with:
          name: sync-report
          path: sync_report.md
          retention-days: 30

      - name: Set workflow status
        run: |
          if [ "${{ steps.check-status.outputs.sync_status }}" == "out-of-sync" ]; then
            echo "❌ Synchronization issues detected. Check the created issue for details."
            exit 1
          else
            echo "✅ Rules are properly synchronized."
          fi
